// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2b1l6Gm92UjUSWN4FeSuAGXItXjZHVuA',
    appId: '1:249079443387:android:d077189fc3a62a1f5ade9e',
    messagingSenderId: '249079443387',
    projectId: 'tetrisz-app',
    storageBucket: 'tetrisz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJdW0S1qRzfUbu64SPOqK1XxQeN7J8WYA',
    appId: '1:249079443387:ios:c10072247e3bf2e55ade9e',
    messagingSenderId: '249079443387',
    projectId: 'tetrisz-app',
    storageBucket: 'tetrisz-app.firebasestorage.app',
    iosBundleId: 'one.tear.tetrisz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJdW0S1qRzfUbu64SPOqK1XxQeN7J8WYA',
    appId: '1:249079443387:ios:c10072247e3bf2e55ade9e',
    messagingSenderId: '249079443387',
    projectId: 'tetrisz-app',
    storageBucket: 'tetrisz-app.firebasestorage.app',
    iosBundleId: 'one.tear.tetrisz',
  );
}
