name = "tetrisz-backend"
main = "src/index.ts"
compatibility_date = "2025-12-01"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

[[durable_objects.bindings]]
name = "LEADERBOARD"
class_name = "LeaderboardDO"

[[durable_objects.bindings]]
name = "PLAYERS"
class_name = "PlayersDO"

[[durable_objects.bindings]]
name = "PRESENCE"
class_name = "PresenceDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["LeaderboardDO"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["PlayersDO"]

[[migrations]]
tag = "v4"
new_sqlite_classes = ["PresenceDO"]

[vars]
FIREBASE_PROJECT_ID = "tetrisz-app"

[observability]
enabled = true
